### ISSUE TITLE
很抱歉找到这里来了，关于您seil的博文

### ISSUE THREAD

**Issue by HongHaiyang** [AlanLi7991/AlanLi7991.github.io#2]
“intelliJ在Mac中文输入法下CpasLock无法小写” 

我看到您的这篇博文，遇到跟你一样的问题，本来很欣喜的觉得问题解决了，没想到“打开系统偏好设置－键盘－快捷键－输入源，将切换到上一个输入法的快捷键设置为F19（通过选择后按一下Caps Lock）”这一步我的 MacBook 只能用组合键来改 “选择上一个输入法” 😂按一下 Caps Lock 没有用。。。🤣真的很无奈，所以想问您现在是怎么解决这个问题的？

在您的博客里没找到电子邮箱地址什么的，所以自作主张在这里开一个 issue，非常抱歉😂

**Comment by AlanLi7991** [comment]
呃。。。现在最新的Mac系统好像已经很少出现这个问题了（我用Pycharm遇到过一次，重启了就好了），需要先把Caps Lock设置成空，然后再用seil映射成F19。。。设置快捷键的时候，点下Caps Lock就可以了。。。
